// CodeContracts
// 
// Copyright (c) Microsoft Corporation
// 
// All rights reserved. 
// 
// MIT License
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED *AS IS*, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

using System;
using System.Collections.Generic;
//using System.Linq;
//using System.Text;
using System.Diagnostics.Contracts;

namespace System {
  // Summary:
  //     Represents the method that will handle an event that has no event data.
  //
  // Parameters:
  //   sender:
  //     The source of the event.
  //
  //   e:
  //     An System.EventArgs that contains no event data.
  public delegate void EventHandler(object sender, EventArgs e);

  // Summary:
  //     Represents the method that will handle an event.
  //
  // Parameters:
  //   sender:
  //     The source of the event.
  //
  //   e:
  //     An System.EventArgs that contains the event data.
  //
  // Type parameters:
  //   TEventArgs:
  //     The type of the event data generated by the event.
  public delegate void EventHandler<TEventArgs>(object sender, TEventArgs e);

}

