// CodeContracts
// 
// Copyright (c) Microsoft Corporation
// 
// All rights reserved. 
// 
// MIT License
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED *AS IS*, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 4/14/2011 10:22:57 AM
namespace LeaderBoardAccess.LeaderboardDataService
{
    
    /// <summary>
    /// There are no comments for LeaderboardEntitySet in the schema.
    /// </summary>
    public partial class LeaderboardEntitySet : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new LeaderboardEntitySet object.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public LeaderboardEntitySet(global::System.Uri serviceRoot) : 
                base(serviceRoot)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            if (typeName.StartsWith("LeaderboardModel", global::System.StringComparison.Ordinal))
            {
                return this.GetType().Assembly.GetType(string.Concat("LeaderBoardAccess.LeaderboardDataService", typeName.Substring(16)), false);
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("LeaderBoardAccess.LeaderboardDataService", global::System.StringComparison.Ordinal))
            {
                return string.Concat("LeaderboardModel.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for Applications in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Application> Applications
        {
            get
            {
                if ((this._Applications == null))
                {
                    this._Applications = base.CreateQuery<Application>("Applications");
                }
                return this._Applications;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Application> _Applications;
        /// <summary>
        /// There are no comments for CostCenters in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<CostCenter> CostCenters
        {
            get
            {
                if ((this._CostCenters == null))
                {
                    this._CostCenters = base.CreateQuery<CostCenter>("CostCenters");
                }
                return this._CostCenters;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<CostCenter> _CostCenters;
        /// <summary>
        /// There are no comments for features in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<feature> features
        {
            get
            {
                if ((this._features == null))
                {
                    this._features = base.CreateQuery<feature>("features");
                }
                return this._features;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<feature> _features;
        /// <summary>
        /// There are no comments for pods in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<pod> pods
        {
            get
            {
                if ((this._pods == null))
                {
                    this._pods = base.CreateQuery<pod>("pods");
                }
                return this._pods;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<pod> _pods;
        /// <summary>
        /// There are no comments for points in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<point> points
        {
            get
            {
                if ((this._points == null))
                {
                    this._points = base.CreateQuery<point>("points");
                }
                return this._points;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<point> _points;
        /// <summary>
        /// There are no comments for UserAggregations in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<UserAggregation> UserAggregations
        {
            get
            {
                if ((this._UserAggregations == null))
                {
                    this._UserAggregations = base.CreateQuery<UserAggregation>("UserAggregations");
                }
                return this._UserAggregations;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<UserAggregation> _UserAggregations;
        /// <summary>
        /// There are no comments for UserAggregationPerDays in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<UserAggregationPerDay> UserAggregationPerDays
        {
            get
            {
                if ((this._UserAggregationPerDays == null))
                {
                    this._UserAggregationPerDays = base.CreateQuery<UserAggregationPerDay>("UserAggregationPerDays");
                }
                return this._UserAggregationPerDays;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<UserAggregationPerDay> _UserAggregationPerDays;
        /// <summary>
        /// There are no comments for Users in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<User> Users
        {
            get
            {
                if ((this._Users == null))
                {
                    this._Users = base.CreateQuery<User>("Users");
                }
                return this._Users;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<User> _Users;
        /// <summary>
        /// There are no comments for Applications in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToApplications(Application application)
        {
            base.AddObject("Applications", application);
        }
        /// <summary>
        /// There are no comments for CostCenters in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToCostCenters(CostCenter costCenter)
        {
            base.AddObject("CostCenters", costCenter);
        }
        /// <summary>
        /// There are no comments for features in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddTofeatures(feature feature)
        {
            base.AddObject("features", feature);
        }
        /// <summary>
        /// There are no comments for pods in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddTopods(pod pod)
        {
            base.AddObject("pods", pod);
        }
        /// <summary>
        /// There are no comments for points in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddTopoints(point point)
        {
            base.AddObject("points", point);
        }
        /// <summary>
        /// There are no comments for UserAggregations in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToUserAggregations(UserAggregation userAggregation)
        {
            base.AddObject("UserAggregations", userAggregation);
        }
        /// <summary>
        /// There are no comments for UserAggregationPerDays in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToUserAggregationPerDays(UserAggregationPerDay userAggregationPerDay)
        {
            base.AddObject("UserAggregationPerDays", userAggregationPerDay);
        }
        /// <summary>
        /// There are no comments for Users in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToUsers(User user)
        {
            base.AddObject("Users", user);
        }
    }
    /// <summary>
    /// There are no comments for LeaderboardModel.Application in the schema.
    /// </summary>
    /// <KeyProperties>
    /// appid
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("appid")]
    public partial class Application
    {
        /// <summary>
        /// Create a new Application object.
        /// </summary>
        /// <param name="appid">Initial value of appid.</param>
        /// <param name="appname">Initial value of appname.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Application CreateApplication(int appid, string appname)
        {
            Application application = new Application();
            application.appid = appid;
            application.appname = appname;
            return application;
        }
        /// <summary>
        /// There are no comments for Property appid in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int appid
        {
            get
            {
                return this._appid;
            }
            set
            {
                this.OnappidChanging(value);
                this._appid = value;
                this.OnappidChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _appid;
        partial void OnappidChanging(int value);
        partial void OnappidChanged();
        /// <summary>
        /// There are no comments for Property appname in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string appname
        {
            get
            {
                return this._appname;
            }
            set
            {
                this.OnappnameChanging(value);
                this._appname = value;
                this.OnappnameChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _appname;
        partial void OnappnameChanging(string value);
        partial void OnappnameChanged();
        /// <summary>
        /// There are no comments for Property appurl in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string appurl
        {
            get
            {
                return this._appurl;
            }
            set
            {
                this.OnappurlChanging(value);
                this._appurl = value;
                this.OnappurlChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _appurl;
        partial void OnappurlChanging(string value);
        partial void OnappurlChanged();
        /// <summary>
        /// There are no comments for Property appowner in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string appowner
        {
            get
            {
                return this._appowner;
            }
            set
            {
                this.OnappownerChanging(value);
                this._appowner = value;
                this.OnappownerChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _appowner;
        partial void OnappownerChanging(string value);
        partial void OnappownerChanged();
        /// <summary>
        /// There are no comments for features in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Collections.ObjectModel.Collection<feature> features
        {
            get
            {
                return this._features;
            }
            set
            {
                if ((value != null))
                {
                    this._features = value;
                }
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Collections.ObjectModel.Collection<feature> _features = new global::System.Collections.ObjectModel.Collection<feature>();
        /// <summary>
        /// There are no comments for pods in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Collections.ObjectModel.Collection<pod> pods
        {
            get
            {
                return this._pods;
            }
            set
            {
                if ((value != null))
                {
                    this._pods = value;
                }
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Collections.ObjectModel.Collection<pod> _pods = new global::System.Collections.ObjectModel.Collection<pod>();
        /// <summary>
        /// There are no comments for UserAggregations in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Collections.ObjectModel.Collection<UserAggregation> UserAggregations
        {
            get
            {
                return this._UserAggregations;
            }
            set
            {
                if ((value != null))
                {
                    this._UserAggregations = value;
                }
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Collections.ObjectModel.Collection<UserAggregation> _UserAggregations = new global::System.Collections.ObjectModel.Collection<UserAggregation>();
        /// <summary>
        /// There are no comments for UserAggregationPerDays in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Collections.ObjectModel.Collection<UserAggregationPerDay> UserAggregationPerDays
        {
            get
            {
                return this._UserAggregationPerDays;
            }
            set
            {
                if ((value != null))
                {
                    this._UserAggregationPerDays = value;
                }
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Collections.ObjectModel.Collection<UserAggregationPerDay> _UserAggregationPerDays = new global::System.Collections.ObjectModel.Collection<UserAggregationPerDay>();
    }
    /// <summary>
    /// There are no comments for LeaderboardModel.CostCenter in the schema.
    /// </summary>
    /// <KeyProperties>
    /// CostCenterName
    /// AddTimestamp
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("CostCenterName", "AddTimestamp")]
    public partial class CostCenter
    {
        /// <summary>
        /// Create a new CostCenter object.
        /// </summary>
        /// <param name="costCenterName">Initial value of CostCenterName.</param>
        /// <param name="addTimestamp">Initial value of AddTimestamp.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static CostCenter CreateCostCenter(string costCenterName, global::System.DateTime addTimestamp)
        {
            CostCenter costCenter = new CostCenter();
            costCenter.CostCenterName = costCenterName;
            costCenter.AddTimestamp = addTimestamp;
            return costCenter;
        }
        /// <summary>
        /// There are no comments for Property CostCenterName in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CostCenterName
        {
            get
            {
                return this._CostCenterName;
            }
            set
            {
                this.OnCostCenterNameChanging(value);
                this._CostCenterName = value;
                this.OnCostCenterNameChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CostCenterName;
        partial void OnCostCenterNameChanging(string value);
        partial void OnCostCenterNameChanged();
        /// <summary>
        /// There are no comments for Property AddTimestamp in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime AddTimestamp
        {
            get
            {
                return this._AddTimestamp;
            }
            set
            {
                this.OnAddTimestampChanging(value);
                this._AddTimestamp = value;
                this.OnAddTimestampChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _AddTimestamp;
        partial void OnAddTimestampChanging(global::System.DateTime value);
        partial void OnAddTimestampChanged();
    }
    /// <summary>
    /// There are no comments for LeaderboardModel.feature in the schema.
    /// </summary>
    /// <KeyProperties>
    /// AppId
    /// FeatureId
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("AppId", "FeatureId")]
    public partial class feature
    {
        /// <summary>
        /// Create a new feature object.
        /// </summary>
        /// <param name="appId">Initial value of AppId.</param>
        /// <param name="featureId">Initial value of FeatureId.</param>
        /// <param name="featureName">Initial value of FeatureName.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static feature Createfeature(int appId, int featureId, string featureName)
        {
            feature feature = new feature();
            feature.AppId = appId;
            feature.FeatureId = featureId;
            feature.FeatureName = featureName;
            return feature;
        }
        /// <summary>
        /// There are no comments for Property AppId in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int AppId
        {
            get
            {
                return this._AppId;
            }
            set
            {
                this.OnAppIdChanging(value);
                this._AppId = value;
                this.OnAppIdChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _AppId;
        partial void OnAppIdChanging(int value);
        partial void OnAppIdChanged();
        /// <summary>
        /// There are no comments for Property FeatureId in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int FeatureId
        {
            get
            {
                return this._FeatureId;
            }
            set
            {
                this.OnFeatureIdChanging(value);
                this._FeatureId = value;
                this.OnFeatureIdChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _FeatureId;
        partial void OnFeatureIdChanging(int value);
        partial void OnFeatureIdChanged();
        /// <summary>
        /// There are no comments for Property FeatureName in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string FeatureName
        {
            get
            {
                return this._FeatureName;
            }
            set
            {
                this.OnFeatureNameChanging(value);
                this._FeatureName = value;
                this.OnFeatureNameChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _FeatureName;
        partial void OnFeatureNameChanging(string value);
        partial void OnFeatureNameChanged();
        /// <summary>
        /// There are no comments for Application in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Application Application
        {
            get
            {
                return this._Application;
            }
            set
            {
                this._Application = value;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Application _Application;
    }
    /// <summary>
    /// There are no comments for LeaderboardModel.pod in the schema.
    /// </summary>
    /// <KeyProperties>
    /// userid
    /// appid
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("userid", "appid")]
    public partial class pod
    {
        /// <summary>
        /// Create a new pod object.
        /// </summary>
        /// <param name="userid">Initial value of userid.</param>
        /// <param name="appid">Initial value of appid.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static pod Createpod(string userid, int appid)
        {
            pod pod = new pod();
            pod.userid = userid;
            pod.appid = appid;
            return pod;
        }
        /// <summary>
        /// There are no comments for Property userid in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string userid
        {
            get
            {
                return this._userid;
            }
            set
            {
                this.OnuseridChanging(value);
                this._userid = value;
                this.OnuseridChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _userid;
        partial void OnuseridChanging(string value);
        partial void OnuseridChanged();
        /// <summary>
        /// There are no comments for Property appid in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int appid
        {
            get
            {
                return this._appid;
            }
            set
            {
                this.OnappidChanging(value);
                this._appid = value;
                this.OnappidChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _appid;
        partial void OnappidChanging(int value);
        partial void OnappidChanged();
        /// <summary>
        /// There are no comments for Application in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Application Application
        {
            get
            {
                return this._Application;
            }
            set
            {
                this._Application = value;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Application _Application;
    }
    /// <summary>
    /// There are no comments for LeaderboardModel.point in the schema.
    /// </summary>
    /// <KeyProperties>
    /// rowid
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("rowid")]
    public partial class point
    {
        /// <summary>
        /// Create a new point object.
        /// </summary>
        /// <param name="rowid">Initial value of rowid.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static point Createpoint(int rowid)
        {
            point point = new point();
            point.rowid = rowid;
            return point;
        }
        /// <summary>
        /// There are no comments for Property userid in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string userid
        {
            get
            {
                return this._userid;
            }
            set
            {
                this.OnuseridChanging(value);
                this._userid = value;
                this.OnuseridChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _userid;
        partial void OnuseridChanging(string value);
        partial void OnuseridChanged();
        /// <summary>
        /// There are no comments for Property appid in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> appid
        {
            get
            {
                return this._appid;
            }
            set
            {
                this.OnappidChanging(value);
                this._appid = value;
                this.OnappidChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _appid;
        partial void OnappidChanging(global::System.Nullable<int> value);
        partial void OnappidChanged();
        /// <summary>
        /// There are no comments for Property featureid in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> featureid
        {
            get
            {
                return this._featureid;
            }
            set
            {
                this.OnfeatureidChanging(value);
                this._featureid = value;
                this.OnfeatureidChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _featureid;
        partial void OnfeatureidChanging(global::System.Nullable<int> value);
        partial void OnfeatureidChanged();
        /// <summary>
        /// There are no comments for Property points in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> points
        {
            get
            {
                return this._points;
            }
            set
            {
                this.OnpointsChanging(value);
                this._points = value;
                this.OnpointsChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _points;
        partial void OnpointsChanging(global::System.Nullable<int> value);
        partial void OnpointsChanged();
        /// <summary>
        /// There are no comments for Property inserttime in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> inserttime
        {
            get
            {
                return this._inserttime;
            }
            set
            {
                this.OninserttimeChanging(value);
                this._inserttime = value;
                this.OninserttimeChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _inserttime;
        partial void OninserttimeChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OninserttimeChanged();
        /// <summary>
        /// There are no comments for Property updatetime in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> updatetime
        {
            get
            {
                return this._updatetime;
            }
            set
            {
                this.OnupdatetimeChanging(value);
                this._updatetime = value;
                this.OnupdatetimeChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _updatetime;
        partial void OnupdatetimeChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnupdatetimeChanged();
        /// <summary>
        /// There are no comments for Property appverhi in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> appverhi
        {
            get
            {
                return this._appverhi;
            }
            set
            {
                this.OnappverhiChanging(value);
                this._appverhi = value;
                this.OnappverhiChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _appverhi;
        partial void OnappverhiChanging(global::System.Nullable<int> value);
        partial void OnappverhiChanged();
        /// <summary>
        /// There are no comments for Property appverlo in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> appverlo
        {
            get
            {
                return this._appverlo;
            }
            set
            {
                this.OnappverloChanging(value);
                this._appverlo = value;
                this.OnappverloChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _appverlo;
        partial void OnappverloChanging(global::System.Nullable<int> value);
        partial void OnappverloChanged();
        /// <summary>
        /// There are no comments for Property osverhi in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> osverhi
        {
            get
            {
                return this._osverhi;
            }
            set
            {
                this.OnosverhiChanging(value);
                this._osverhi = value;
                this.OnosverhiChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _osverhi;
        partial void OnosverhiChanging(global::System.Nullable<int> value);
        partial void OnosverhiChanged();
        /// <summary>
        /// There are no comments for Property osverlo in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> osverlo
        {
            get
            {
                return this._osverlo;
            }
            set
            {
                this.OnosverloChanging(value);
                this._osverlo = value;
                this.OnosverloChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _osverlo;
        partial void OnosverloChanging(global::System.Nullable<int> value);
        partial void OnosverloChanged();
        /// <summary>
        /// There are no comments for Property rowid in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int rowid
        {
            get
            {
                return this._rowid;
            }
            set
            {
                this.OnrowidChanging(value);
                this._rowid = value;
                this.OnrowidChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _rowid;
        partial void OnrowidChanging(int value);
        partial void OnrowidChanged();
    }
    /// <summary>
    /// There are no comments for LeaderboardModel.UserAggregation in the schema.
    /// </summary>
    /// <KeyProperties>
    /// userid
    /// appid
    /// featureid
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("userid", "appid", "featureid")]
    public partial class UserAggregation
    {
        /// <summary>
        /// Create a new UserAggregation object.
        /// </summary>
        /// <param name="userid">Initial value of userid.</param>
        /// <param name="appid">Initial value of appid.</param>
        /// <param name="featureid">Initial value of featureid.</param>
        /// <param name="totalpoints">Initial value of totalpoints.</param>
        /// <param name="uses">Initial value of uses.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static UserAggregation CreateUserAggregation(string userid, int appid, int featureid, int totalpoints, int uses)
        {
            UserAggregation userAggregation = new UserAggregation();
            userAggregation.userid = userid;
            userAggregation.appid = appid;
            userAggregation.featureid = featureid;
            userAggregation.totalpoints = totalpoints;
            userAggregation.uses = uses;
            return userAggregation;
        }
        /// <summary>
        /// There are no comments for Property userid in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string userid
        {
            get
            {
                return this._userid;
            }
            set
            {
                this.OnuseridChanging(value);
                this._userid = value;
                this.OnuseridChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _userid;
        partial void OnuseridChanging(string value);
        partial void OnuseridChanged();
        /// <summary>
        /// There are no comments for Property appid in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int appid
        {
            get
            {
                return this._appid;
            }
            set
            {
                this.OnappidChanging(value);
                this._appid = value;
                this.OnappidChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _appid;
        partial void OnappidChanging(int value);
        partial void OnappidChanged();
        /// <summary>
        /// There are no comments for Property featureid in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int featureid
        {
            get
            {
                return this._featureid;
            }
            set
            {
                this.OnfeatureidChanging(value);
                this._featureid = value;
                this.OnfeatureidChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _featureid;
        partial void OnfeatureidChanging(int value);
        partial void OnfeatureidChanged();
        /// <summary>
        /// There are no comments for Property totalpoints in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int totalpoints
        {
            get
            {
                return this._totalpoints;
            }
            set
            {
                this.OntotalpointsChanging(value);
                this._totalpoints = value;
                this.OntotalpointsChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _totalpoints;
        partial void OntotalpointsChanging(int value);
        partial void OntotalpointsChanged();
        /// <summary>
        /// There are no comments for Property uses in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int uses
        {
            get
            {
                return this._uses;
            }
            set
            {
                this.OnusesChanging(value);
                this._uses = value;
                this.OnusesChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _uses;
        partial void OnusesChanging(int value);
        partial void OnusesChanged();
        /// <summary>
        /// There are no comments for Application in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Application Application
        {
            get
            {
                return this._Application;
            }
            set
            {
                this._Application = value;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Application _Application;
    }
    /// <summary>
    /// There are no comments for LeaderboardModel.UserAggregationPerDay in the schema.
    /// </summary>
    /// <KeyProperties>
    /// userid
    /// appid
    /// featureid
    /// eventDate
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("userid", "appid", "featureid", "eventDate")]
    public partial class UserAggregationPerDay
    {
        /// <summary>
        /// Create a new UserAggregationPerDay object.
        /// </summary>
        /// <param name="userid">Initial value of userid.</param>
        /// <param name="appid">Initial value of appid.</param>
        /// <param name="featureid">Initial value of featureid.</param>
        /// <param name="eventDate">Initial value of eventDate.</param>
        /// <param name="totalpoints">Initial value of totalpoints.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static UserAggregationPerDay CreateUserAggregationPerDay(string userid, int appid, int featureid, global::System.DateTime eventDate, int totalpoints)
        {
            UserAggregationPerDay userAggregationPerDay = new UserAggregationPerDay();
            userAggregationPerDay.userid = userid;
            userAggregationPerDay.appid = appid;
            userAggregationPerDay.featureid = featureid;
            userAggregationPerDay.eventDate = eventDate;
            userAggregationPerDay.totalpoints = totalpoints;
            return userAggregationPerDay;
        }
        /// <summary>
        /// There are no comments for Property userid in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string userid
        {
            get
            {
                return this._userid;
            }
            set
            {
                this.OnuseridChanging(value);
                this._userid = value;
                this.OnuseridChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _userid;
        partial void OnuseridChanging(string value);
        partial void OnuseridChanged();
        /// <summary>
        /// There are no comments for Property appid in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int appid
        {
            get
            {
                return this._appid;
            }
            set
            {
                this.OnappidChanging(value);
                this._appid = value;
                this.OnappidChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _appid;
        partial void OnappidChanging(int value);
        partial void OnappidChanged();
        /// <summary>
        /// There are no comments for Property featureid in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int featureid
        {
            get
            {
                return this._featureid;
            }
            set
            {
                this.OnfeatureidChanging(value);
                this._featureid = value;
                this.OnfeatureidChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _featureid;
        partial void OnfeatureidChanging(int value);
        partial void OnfeatureidChanged();
        /// <summary>
        /// There are no comments for Property eventDate in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime eventDate
        {
            get
            {
                return this._eventDate;
            }
            set
            {
                this.OneventDateChanging(value);
                this._eventDate = value;
                this.OneventDateChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _eventDate;
        partial void OneventDateChanging(global::System.DateTime value);
        partial void OneventDateChanged();
        /// <summary>
        /// There are no comments for Property totalpoints in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int totalpoints
        {
            get
            {
                return this._totalpoints;
            }
            set
            {
                this.OntotalpointsChanging(value);
                this._totalpoints = value;
                this.OntotalpointsChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _totalpoints;
        partial void OntotalpointsChanging(int value);
        partial void OntotalpointsChanged();
        /// <summary>
        /// There are no comments for Application in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Application Application
        {
            get
            {
                return this._Application;
            }
            set
            {
                this._Application = value;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Application _Application;
    }
    /// <summary>
    /// There are no comments for LeaderboardModel.User in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Alias
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Alias")]
    public partial class User
    {
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="fullname">Initial value of Fullname.</param>
        /// <param name="alias">Initial value of Alias.</param>
        /// <param name="updateTimestamp">Initial value of UpdateTimestamp.</param>
        /// <param name="nonADAccount">Initial value of NonADAccount.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static User CreateUser(string fullname, string alias, global::System.DateTime updateTimestamp, bool nonADAccount)
        {
            User user = new User();
            user.Fullname = fullname;
            user.Alias = alias;
            user.UpdateTimestamp = updateTimestamp;
            user.NonADAccount = nonADAccount;
            return user;
        }
        /// <summary>
        /// There are no comments for Property Fullname in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Fullname
        {
            get
            {
                return this._Fullname;
            }
            set
            {
                this.OnFullnameChanging(value);
                this._Fullname = value;
                this.OnFullnameChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Fullname;
        partial void OnFullnameChanging(string value);
        partial void OnFullnameChanged();
        /// <summary>
        /// There are no comments for Property Alias in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Alias
        {
            get
            {
                return this._Alias;
            }
            set
            {
                this.OnAliasChanging(value);
                this._Alias = value;
                this.OnAliasChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Alias;
        partial void OnAliasChanging(string value);
        partial void OnAliasChanged();
        /// <summary>
        /// There are no comments for Property CSP in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CSP
        {
            get
            {
                return this._CSP;
            }
            set
            {
                this.OnCSPChanging(value);
                this._CSP = value;
                this.OnCSPChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CSP;
        partial void OnCSPChanging(string value);
        partial void OnCSPChanged();
        /// <summary>
        /// There are no comments for Property Discipline in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Discipline
        {
            get
            {
                return this._Discipline;
            }
            set
            {
                this.OnDisciplineChanging(value);
                this._Discipline = value;
                this.OnDisciplineChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Discipline;
        partial void OnDisciplineChanging(string value);
        partial void OnDisciplineChanged();
        /// <summary>
        /// There are no comments for Property CostCenterName in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CostCenterName
        {
            get
            {
                return this._CostCenterName;
            }
            set
            {
                this.OnCostCenterNameChanging(value);
                this._CostCenterName = value;
                this.OnCostCenterNameChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CostCenterName;
        partial void OnCostCenterNameChanging(string value);
        partial void OnCostCenterNameChanged();
        /// <summary>
        /// There are no comments for Property UpdateTimestamp in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime UpdateTimestamp
        {
            get
            {
                return this._UpdateTimestamp;
            }
            set
            {
                this.OnUpdateTimestampChanging(value);
                this._UpdateTimestamp = value;
                this.OnUpdateTimestampChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _UpdateTimestamp;
        partial void OnUpdateTimestampChanging(global::System.DateTime value);
        partial void OnUpdateTimestampChanged();
        /// <summary>
        /// There are no comments for Property NonADAccount in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool NonADAccount
        {
            get
            {
                return this._NonADAccount;
            }
            set
            {
                this.OnNonADAccountChanging(value);
                this._NonADAccount = value;
                this.OnNonADAccountChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _NonADAccount;
        partial void OnNonADAccountChanging(bool value);
        partial void OnNonADAccountChanged();
    }
}
