// CodeContracts
// 
// Copyright (c) Microsoft Corporation
// 
// All rights reserved. 
// 
// MIT License
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED *AS IS*, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

// <auto-generated>
// This file should only contain assembly level attributes.
// Do not add any class or struct definitions as it may disable the ability of the tool to
// update the file.
// </auto-generated>

using System;

using Microsoft.Research.ClousotRegression;
#if false
[assembly: RegressionOutcome("Member 'priv' has less visibility than the enclosing method 'BasicInfrastructure.VisibilityViolations.Test2'.")]
[assembly: RegressionOutcome("Member 'intern' has less visibility than the enclosing method 'BasicInfrastructure.VisibilityViolations.Test2'.")]
[assembly: RegressionOutcome("Member 'priv' has less visibility than the enclosing method 'BasicInfrastructure.VisibilityViolations.Test3'.")]
[assembly: RegressionOutcome("Member 'prot' has less visibility than the enclosing method 'BasicInfrastructure.VisibilityViolations.Test3'.")]
[assembly: RegressionOutcome("Member 'priv' has less visibility than the enclosing method 'BasicInfrastructure.VisibilityViolations.Test4'.")]
[assembly: RegressionOutcome("Member 'prot' has less visibility than the enclosing method 'BasicInfrastructure.VisibilityViolations.Test4'.")]
[assembly: RegressionOutcome("Member 'intern' has less visibility than the enclosing method 'BasicInfrastructure.VisibilityViolations.Test4'.")]
[assembly: RegressionOutcome("Member 'priv' has less visibility than the enclosing method 'BasicInfrastructure.VisibilityViolations.Test5'.")]
[assembly: RegressionOutcome("Member 'prot' has less visibility than the enclosing method 'BasicInfrastructure.VisibilityViolations.Test5'.")]
[assembly: RegressionOutcome("Member 'intern' has less visibility than the enclosing method 'BasicInfrastructure.VisibilityViolations.Test5'.")]
[assembly: RegressionOutcome("Member 'priv' has less visibility than the enclosing method 'BasicInfrastructure.VisibilityViolationsInternal.Test2'.")]
[assembly: RegressionOutcome("Member 'priv' has less visibility than the enclosing method 'BasicInfrastructure.VisibilityViolationsInternal.Test3'.")]
[assembly: RegressionOutcome("Member 'prot' has less visibility than the enclosing method 'BasicInfrastructure.VisibilityViolationsInternal.Test3'.")]
[assembly: RegressionOutcome("Member 'priv' has less visibility than the enclosing method 'BasicInfrastructure.VisibilityViolationsInternal.Test4'.")]
[assembly: RegressionOutcome("Member 'prot' has less visibility than the enclosing method 'BasicInfrastructure.VisibilityViolationsInternal.Test4'.")]
[assembly: RegressionOutcome("Member 'priv' has less visibility than the enclosing method 'BasicInfrastructure.VisibilityViolationsInternal.Test5'.")]
[assembly: RegressionOutcome("Member 'prot' has less visibility than the enclosing method 'BasicInfrastructure.VisibilityViolationsInternal.Test5'.")]
#endif
[assembly: RegressionOutcome("Method 'BasicInfrastructure.OverrideViolations.ToString' overrides 'System.Object.ToString', thus cannot add Requires.")]
